{"name": "test_failed_update_due_to_an_invalid_pet_ID", "status": "passed", "start": 1756138082115, "stop": 1756138082142, "uuid": "894b7895-0a54-4046-8daf-1b924e7a14e3", "historyId": "c2c9d3c2e5e33dba873253f93e369b72", "testCaseId": "c2c9d3c2e5e33dba873253f93e369b72", "fullName": "tests_type.test_put#test_failed_update_due_to_an_invalid_pet_ID", "labels": [{"name": "parentSuite", "value": "tests_type"}, {"name": "suite", "value": "test_put"}, {"name": "host", "value": "DESKTOP-RMH21D8"}, {"name": "thread", "value": "11072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests_type.test_put"}], "titlePath": ["tests_type", "test_put.py"]}